name: nodejs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - run: npm ci

      # Check if build and package artifacts can still be generated
      - run: npm run build

      # Check linting and typing
      - run: npm run lint
      - run: npm run types
